on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: feature/v2

      - name: Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build:sb

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: storybook-static

  deploy:
    environment:
      name: storybook
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: storybook-static

      - name: Deploy
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          build-dir: './storybook-static'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
